### ISSUE TITLE
Amended code for python 2.7

### ISSUE THREAD

**Issue by sujitvasanth** [danjperron/LX16A#1]
Hi Danjperron

Thankyou for producing such a comprehensive library.
I wanted a simplified version that runs on python 2.7 and that is shorter...
My version works on windows and I thought it may be useful to others who wanted to work in python 2.7..

[LX16Awalk5.zip](https://github.com/danjperron/LX16A/files/2655544/LX16Awalk5.zip)

https://drive.google.com/file/d/1e9ufrIlQSM1uMu_6oj4CiufyW1GLamkT/view?usp=sharing

**Comment by danjperron** [comment]
Hi sujtvasanth,

  Thanks but, simplify the code make it very hard to read. Why do you want to simplify it? (MicroPython?)

I  know my comments are in french but you should put some on yours just to explain what each function does! and please put space line between functions.

 You maybe right I don't code with python 2.7 anymore. I.M.O. it's obsolete! 

In 10 years you will look at your  code and try to figure out why I have a number one in function moveServo for parameters.  I should have put remarks just to figure out what I was doing!

Better declare function literally than just put a number because it is way easier to pinpoint  if you have  the correct function code by looking at the text declaration than a simple number.

This is my opinion but you are free to do what you want.

Daniel
